# Generated by Django 5.2.3 on 2025-06-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_ia', '0002_alter_subir_mp4_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('nivel_atencion', models.IntegerField()),
            ],
        ),
    ]
