# Generated by Django 5.2.3 on 2025-06-26 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_ia', '0005_reportehistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitoreo',
            old_name='nivel_atencion',
            new_name='atencion',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='nombre_clase',
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='distraccion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='somnolencia',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
