# Generated by Django 5.2.3 on 2025-06-23 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('nivel_atencion', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
