# Generated by Django 5.2.3 on 2025-06-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reconocimiento', '0002_delete_reportehistorico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Docente', 'Docente'), ('Observador', 'Observador')], max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=10)),
                ('ultimo_acceso', models.CharField(max_length=50)),
            ],
        ),
    ]
