# Generated by Django 5.2.3 on 2025-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
