# Generated by Django 5.2.3 on 2025-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconocimiento', '0005_alter_usuario_correo_alter_usuario_ultimo_acceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
